language: node_js
node_js:
- '4.4'
- '6.1'
deploy:
  provider: npm
  email: sebastian@urbantalk.se
  api_key:
    secure: IEQop/cRbiZArEjJtNzlexi1+hj6mAqHV4CAtb4+szPIBL3kKFcjlnLVbAqjShGwSkzZD+qlMy2xTKshk9cF/J3YiFjDx1na16B7nAWKDuunUUQDChLGtWnF8Y7MAgQ/KCupKZDYSNj4jMdwl6JxlLLR3Oe2Z3jf8QUW0d3069VioNm9qIzEPl37qoHOrMy0YHI+K2/OmfrhMNNu+rcsVpWevNuyes81npqUDKBzoxHXfeJAF9THsmP+/AP1/XAorl8PLrLCdy3Qcl4zuBUX4Z8Cjz73zbxU9OlZPrdjnvR5jreLY0B8siU6PQ3d/bw4efNFHOUcy0CuwLNNnI8FuoUe/A7WUKyrp86HTdhNA/HmL1TY/ahm+BaJyixQmtpmw0xbp9j2hPdTvB5meMIfl51jHGwwzrYXdljrj6NtmWT15UNyaiscK+1vklBmZpDeZxsq400Vc/Rx51Je0AElVSGbWiTQ/CVk2IpOwsYdCL7xGKvmvxXwHTXhjJp36k7WidYVfWce5vUSxmd3+uJa1xDKEOjd5Z8EA4Ymqd3/5alCqmAPoHlIcY8vE0PghQJbll6TZJW8o4NhUNYrINEzA8ICozr+t8pguPAbjKkqKpL/N0u5VWFaYOT5eMCGmBXXCBWsk6vdQNUJHMXAfoAtEgYmg5ckHmvq8kS1j/RePbQ=
  on:
    tags: true
    repo: jhsware/isomorphic-schema
